version: '3.8'

services:
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn TravellingCompanion.wsgi:application -w 2 -b :8000 --reload
    volumes:
      - ./app:/home/app/web
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "24:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: