# Generated by Django 4.0 on 2021-12-21 22:40

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created_by',
                                                 to='core.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_updated_by',
                                                 to='core.user')),
            ],
            options={
                'verbose_name': 'Destination',
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True,
                                            validators=[django.core.validators.EmailValidator()])),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created_by',
                                                 to='core.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_updated_by',
                                                 to='core.user')),
                ('user', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.SET_NULL,
                                           to='core.user')),
            ],
            options={
                'verbose_name': 'Passenger',
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_created_by',
                                                 to='core.user')),
            ],
            options={
                'verbose_name': 'Trip',
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='TripPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('passenger', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.CASCADE,
                                                to='travel.passenger')),
                ('trip', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           to='travel.trip')),
            ],
            options={
                'db_table': 'trip_passenger',
            },
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('destination', models.ForeignKey(blank=True, null=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  to='travel.destination')),
                ('trip', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           to='travel.trip')),
            ],
            options={
                'db_table': 'trip_destination',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(related_name='trip_destinations',
                                         through='travel.TripDestination', to='travel.Destination'),
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(related_name='trip_passengers',
                                         through='travel.TripPassenger', to='travel.Passenger'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_updated_by', to='core.user'),
        ),
    ]
